from context.shared.domain.exception.error_base import ErrorBase


class InternalBaseError(ErrorBase):
    pass
